#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-File-Tail
Version  : 1.3
Release  : 12
URL      : https://cpan.metacpan.org/authors/id/M/MG/MGRABNAR/File-Tail-1.3.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/M/MG/MGRABNAR/File-Tail-1.3.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libf/libfile-tail-perl/libfile-tail-perl_1.3-4.debian.tar.xz
Summary  : unknown
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-File-Tail-license = %{version}-%{release}
Requires: perl-File-Tail-perl = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
The File::Tail module is designed for reading files which are continously
appended to (the name comes from the tail -f directive). Usualy such files are
logfiles of some description.

%package dev
Summary: dev components for the perl-File-Tail package.
Group: Development
Provides: perl-File-Tail-devel = %{version}-%{release}
Requires: perl-File-Tail = %{version}-%{release}

%description dev
dev components for the perl-File-Tail package.


%package license
Summary: license components for the perl-File-Tail package.
Group: Default

%description license
license components for the perl-File-Tail package.


%package perl
Summary: perl components for the perl-File-Tail package.
Group: Default
Requires: perl-File-Tail = %{version}-%{release}

%description perl
perl components for the perl-File-Tail package.


%prep
%setup -q -n File-Tail-1.3
cd %{_builddir}
tar xf %{_sourcedir}/libfile-tail-perl_1.3-4.debian.tar.xz
cd %{_builddir}/File-Tail-1.3
mkdir -p deblicense/
cp -r %{_builddir}/debian/* %{_builddir}/File-Tail-1.3/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-File-Tail
cp %{_builddir}/debian/copyright %{buildroot}/usr/share/package-licenses/perl-File-Tail/ec68fd4ed1ea3b4efa782f60f3d4f06547348bd5
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/File::Tail.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-File-Tail/ec68fd4ed1ea3b4efa782f60f3d4f06547348bd5

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.30.3/File/Tail.pm
